#     -   -   -   -   -   -   -   -   -
#              - CropsPlus -
#              by Binekrasik
#     -   -   -   -   -   -   -   -   -
#     > Configuration File

# ! Disclaimer: Please don't use the TAB key in .yml configuration files, because the Bukkit can't deal with it. Seriously, don't use the TAB

# -> If you don't want the feature to be enabled in some worlds, you can list them here.
# ! This is CASE-SENSITIVE
disabled-worlds:
  - Example
  - World2
  - Something

# -> You can list farmland-protected worlds here.
# [i] Protecting farmland means that an entity will not be able to turn it into dirt if it jumps on it.
# ! This is CASE-SENSITIVE
farmland-protection:
  - Example
  - Something
  - World2

#     -   -   -   -   -   -
#                      
#       REPLANTING CROPS   
#                      
#     -   -   -   -   -   -

# -> Replanting crops by right-clicking on them
# > Default value: true
enable-rightclick-replant: true


#     -   -   -   -   -   -
#                      
#       GROWTH PARTICLES
#                      
#     -   -   -   -   -   -

# -> Displaying growth particles from crop's age
# ! If you (or others) are experiencing delays near crops, I recommend turning off or reducing particles.
growth-particles:
  # -> Enable particles?
  # > Default value: true
  enabled: true

  # -> How far should the particles be able to see?
  # > Default value: 15
  display-radius: 15

  # -> How many particles to display per 5 ticks?
  # > Default value: 4
  amount: 4

  # -> What colour should the particles be once the crop has grown?
  # > Default value: 155, 255, 100
  grown-rgb: 155, 255, 100

  # -> What colour should the particles be during crop stages?
  # [i] Beetroots have only 4 stages. For this, the stages that be used are marked as Beetroot.
  # > Default value: 50, 155, 255
  stage1-rgb: 255, 255, 255 #Beetroot
  stage2-rgb: 255, 171, 171
  stage3-rgb: 255, 225, 143 #Beetroot
  stage4-rgb: 202, 255, 135
  stage5-rgb: 120, 255, 127 #Beetroot
  stage6-rgb: 117, 255, 255
  stage7-rgb: 97, 179, 255 #Beetroot