name: CropsPlus
description: Have a better crops, by Binekrasik!
main: dev.binekrasik.cropsplus.CropsPlus
author: Binekrasik
version: 1.2.1
api-version: 1.14
commands:
  crops:
    description: Main command of CropsPlus plugin.